server:
  port: 8081
  error:
    include-stacktrace: NEVER
 
spring:
  datasource:
    url: jdbc:h2:~/fiapdb/cartao-fiap;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console: 
      enabled: true
  http:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
      
springdoc:
  api-docs:
    path: /api-docs  
    
    
    