INSERT INTO CLIENTES(nome, matricula, data_cadastro, data_atualizacao) VALUES('JOAO DA SILVA', '123456789', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CLIENTES(nome, matricula, data_cadastro, data_atualizacao) VALUES('MARIA DA SILVA', '456789123', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO USUARIOS(email, senha, cliente_id, data_criacao, data_alteracao) VALUES('aluno@fiap.com.br', '$2a$10$sFKmbxbG4ryhwPNx/l3pgOJSt.fW1z6YcUnuE2X8APA/Z3NI/oSpq', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO USUARIOS(email, senha, cliente_id, data_criacao, data_alteracao) VALUES('gestor@fiap.com.br', '$2a$10$sFKmbxbG4ryhwPNx/l3pgOJSt.fW1z6YcUnuE2X8APA/Z3NI/oSpq', null, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO USUARIOS(email, senha, cliente_id, data_criacao, data_alteracao) VALUES('autoriza@visa.com.br', '$2a$10$sFKmbxbG4ryhwPNx/l3pgOJSt.fW1z6YcUnuE2X8APA/Z3NI/oSpq', null, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO USUARIOS(email, senha, cliente_id, data_criacao, data_alteracao) VALUES('aluno2@fiap.com.br', '$2a$10$sFKmbxbG4ryhwPNx/l3pgOJSt.fW1z6YcUnuE2X8APA/Z3NI/oSpq', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO PERFIL(id, nome) VALUES(1, 'ROLE_ALUNO');
INSERT INTO PERFIL(id, nome) VALUES(2, 'ROLE_GESTOR');
INSERT INTO PERFIL(id, nome) VALUES(3, 'ROLE_ADMIN_CARTAO');

INSERT INTO USUARIOS_PERFIS(usuario_id, perfis_id) VALUES(1, 1);
INSERT INTO USUARIOS_PERFIS(usuario_id, perfis_id) VALUES(2, 2);
INSERT INTO USUARIOS_PERFIS(usuario_id, perfis_id) VALUES(3, 3);
INSERT INTO USUARIOS_PERFIS(usuario_id, perfis_id) VALUES(4, 1);

INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(1, 616.06,'2022-01-03', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(1, 167.96,'2022-01-05', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(1, 557.68,'2022-02-23', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(1, 721.45,'2022-02-15', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(1, 538.55,'2022-02-12', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(1, 359.94,'2022-03-07', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(1, 323.86,'2022-03-08', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(1, 962.07,'2022-03-07', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(1, 647.94,'2022-04-20', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(1, 463.19,'2022-04-08', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(1, 766.54,'2022-04-15', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(1, 636.26,'2022-05-12', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(1, 534.79,'2022-05-24', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(1, 998.63,'2022-05-20', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(1, 697.00,'2022-06-30', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(1, 572.12,'2022-06-30', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(1, 709.42,'2022-06-05', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(1, 462.39,'2022-07-28', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(1, 922.52,'2022-07-01', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(1, 336.53,'2022-08-13', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(2, 466.61,'2022-01-11', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(2, 996.95,'2022-01-08', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(2, 489.31,'2022-02-05', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(2, 222.12,'2022-02-08', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(2, 134.87,'2022-03-09', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(2, 704.62,'2022-03-06', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(2, 696.43,'2022-03-14', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(2, 318.60,'2022-04-15', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(2, 548.18,'2022-04-07', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(2, 173.91,'2022-05-14', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(2, 722.95,'2022-05-06', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(2, 719.63,'2022-06-10', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(2, 342.65,'2022-06-08', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(2, 492.92,'2022-07-11', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(2, 562.00,'2022-07-10', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMPRAS(CLIENTE_ID, VALOR, DATA, SITUACAO, DATA_INCLUSAO, DATA_ATUALIZACAO) VALUES(2, 685.58,'2022-08-05', 'AUTORIZADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
