create table CARTOES(
	"ID" BIGINT AUTO_INCREMENT PRIMARY KEY, 
	"DATA_VENCIMENTO" DATE NOT NULL, 
	"LIMITE" DECIMAL(6, 2) NOT NULL, 
	"NUMERO" VARCHAR(20) NOT NULL, 
	"SITUACAO" VARCHAR(30) NOT NULL, 
	"DATA_CADASTRO" TIMESTAMP NOT NULL, 
	"DATA_ATUALIZACAO" TIMESTAMP NOT NULL,
	"CLIENTE_ID" BIGINT NOT NULL
);

alter table CARTOES
ADD FOREIGN KEY ("CLIENTE_ID") REFERENCES CLIENTES("ID");
