create table FATURAS(
	"ID" BIGINT AUTO_INCREMENT PRIMARY KEY, 
	"DATA_VENCIMENTO" DATE NOT NULL, 
	"SITUACAO" VARCHAR(30) NOT NULL, 
	"DATA_INCLUSAO" TIMESTAMP NOT NULL, 
	"DATA_ATUALIZACAO" TIMESTAMP NOT NULL,
	"CLIENTE_ID" BIGINT NOT NULL
);

alter table FATURAS
ADD FOREIGN KEY ("CLIENTE_ID") REFERENCES CLIENTES("ID");
