create table COMPRAS(
	"ID" BIGINT AUTO_INCREMENT PRIMARY KEY, 
	"VALOR" DECIMAL(6,2) NOT NULL, 
	"DATA" DATE NOT NULL, 
	"SITUACAO" VARCHAR(30) NOT NULL, 
	"DATA_INCLUSAO" TIMESTAMP NOT NULL, 
	"DATA_ATUALIZACAO" TIMESTAMP NOT NULL,
	"CARTAO_ID" BIGINT NOT NULL, 
	"FATURA_ID" BIGINT
);

alter table COMPRAS
ADD FOREIGN KEY ("CARTAO_ID") REFERENCES CARTOES("ID");

alter table COMPRAS
ADD FOREIGN KEY ("FATURA_ID") REFERENCES FATURAS("ID");
